table Discharges_2001-2024_bivariate_final
	lineageTag: b87c51f5-445f-4993-9e4e-023a9fd98378

	measure Total_Filas = COUNTROWS('Discharges_2001-2024_bivariate_final')
		formatString: 0
		lineageTag: dda4b29f-885b-4252-ac01-16972c1f9e25

	measure 'Average LOS (capped)' = AVERAGE('Discharges_2001-2024_bivariate_final'[LOS_capped])
		lineageTag: 5f024c16-c63e-45d3-a6c1-df7d56166204

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median LOS (capped)' = MEDIAN('Discharges_2001-2024_bivariate_final'[LOS_capped])
		lineageTag: 3d5483bf-4bcc-45a5-a6c6-ab44f45e465e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median LOS (capped) v2' = PERCENTILE.INC('Discharges_2001-2024_bivariate_final'[LOS_capped], 0.5)
		lineageTag: 1f34e15a-ed21-4a45-8e03-c745dc62e44e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sex
		dataType: string
		lineageTag: 78613157-0309-4e85-a079-099b9ebc7076
		summarizeBy: none
		sourceColumn: sex

		annotation SummarizationSetBy = Automatic

	column age
		dataType: string
		lineageTag: 238a7469-caed-4e69-aabf-0b0482d8e70c
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column 'health insurance'
		dataType: string
		lineageTag: 6d5c7f70-427a-4c0a-8a7c-5674d7cb5155
		summarizeBy: none
		sourceColumn: health insurance

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'healthcare facility type'
		dataType: string
		lineageTag: b4c945e0-c558-45b7-b828-a3d6e27110c6
		summarizeBy: none
		sourceColumn: healthcare facility type

		annotation SummarizationSetBy = Automatic

	column 'healthcare facility name'
		dataType: string
		lineageTag: 0931337e-9f2c-4151-b124-dc24b898eba8
		summarizeBy: none
		sourceColumn: healthcare facility name

		annotation SummarizationSetBy = Automatic

	column 'discharge condition'
		dataType: string
		lineageTag: 7a0f7247-0cb2-48d4-bfae-7147e86dd2bc
		summarizeBy: none
		sourceColumn: discharge condition

		annotation SummarizationSetBy = Automatic

	column 'primary diagnosis name'
		dataType: string
		lineageTag: 7b2d46b8-a550-490d-9432-3ceed95cbcc7
		summarizeBy: none
		sourceColumn: primary diagnosis name

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: f7183b3e-ded1-426d-a040-19596747de47
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column 'chapter names'
		dataType: string
		lineageTag: 0881e8cf-ef02-45f2-ba1c-7c90a4f27796
		summarizeBy: none
		sourceColumn: chapter names

		annotation SummarizationSetBy = Automatic

	column LOS_capped
		dataType: int64
		formatString: 0
		lineageTag: cafbf55e-d479-4a4c-9c13-e8257da7ad49
		summarizeBy: sum
		sourceColumn: LOS_capped

		annotation SummarizationSetBy = Automatic

	column 'group names'
		dataType: string
		lineageTag: 46782c87-4ab1-46ef-bb20-81daea934f80
		summarizeBy: none
		sourceColumn: group names

		annotation SummarizationSetBy = Automatic

	partition Discharges_2001-2024_bivariate_final = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\mpodu\Desktop\Curso Data Science DL\EDAHospDischarges_Chile2001-2024\data\processed\Discharges_2001-2024_bivariate_final.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Filtered Rows" = Table.SelectRows(Source, each true),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"length of stay", "primary diagnosis code", "chapter codes", "group codes"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

