table Fact_Discharges
	lineageTag: 0a621791-09be-4bb1-97ef-c4e19f68f8d4

	measure 'Mortality Rate' =
			
			DIVIDE(
			    CALCULATE(COUNTROWS('Fact_Discharges'), 'Fact_Discharges'[discharge condition] = "Deceased"),
			    COUNTROWS('Fact_Discharges')
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b1729c5a-5a16-4a14-a3c0-25645dcf5ee1

	measure 'Average LOS (capped)' = AVERAGE('Fact_Discharges'[LOS_capped])
		lineageTag: 229cb908-d005-4d66-8819-ffcf7d5cf0b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Median =
			
			VAR FreqTable =
			    ADDCOLUMNS(
			        VALUES('Fact_Discharges'[LOS_capped]),
			        "Freq", CALCULATE(COUNTROWS('Fact_Discharges'))
			    )
			VAR TotalCount = SUMX(FreqTable, [Freq])
			VAR CumulativeTable =
			    ADDCOLUMNS(
			        FreqTable,
			        "CumFreq",
			            VAR CurrentVal = 'Fact_Discharges'[LOS_capped]
			            RETURN SUMX(FILTER(FreqTable, 'Fact_Discharges'[LOS_capped] <= CurrentVal), [Freq])
			    )
			RETURN
			    MINX(
			        FILTER(CumulativeTable, [CumFreq] >= TotalCount / 2),
			        'Fact_Discharges'[LOS_capped]
			    )
		formatString: 0
		lineageTag: bbe7a404-7bc4-4abe-bae1-1ababd11edb6

	measure 'Diagnosis Prevalence %' =
			
			DIVIDE(
			    COUNTROWS('Fact_Discharges'),
			    CALCULATE(
			        COUNTROWS('Fact_Discharges'),
			        ALL('Diagnosis')
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 752f8660-edac-48c0-a203-bb53cba15e68

	measure P25 =
			
			VAR FreqTable =
			    ADDCOLUMNS(
			        VALUES('Fact_Discharges'[LOS_capped]),
			        "Freq", CALCULATE(COUNTROWS('Fact_Discharges'))
			    )
			VAR TotalCount = SUMX(FreqTable, [Freq])
			VAR CumulativeTable =
			    ADDCOLUMNS(
			        FreqTable,
			        "CumFreq",
			            VAR CurrentVal = 'Fact_Discharges'[LOS_capped]
			            RETURN SUMX(FILTER(FreqTable, 'Fact_Discharges'[LOS_capped] <= CurrentVal), [Freq])
			    )
			RETURN
			    MINX(
			        FILTER(CumulativeTable, [CumFreq] >= TotalCount * 0.25),
			        'Fact_Discharges'[LOS_capped]
			    )
		formatString: 0
		lineageTag: 0f9c42a5-d7d7-4015-a87b-9d7cdb773fac

	measure P75 =
			
			VAR FreqTable =
			    ADDCOLUMNS(
			        VALUES('Fact_Discharges'[LOS_capped]),
			        "Freq", CALCULATE(COUNTROWS('Fact_Discharges'))
			    )
			VAR TotalCount = SUMX(FreqTable, [Freq])
			VAR CumulativeTable =
			    ADDCOLUMNS(
			        FreqTable,
			        "CumFreq",
			            VAR CurrentVal = 'Fact_Discharges'[LOS_capped]
			            RETURN SUMX(FILTER(FreqTable, 'Fact_Discharges'[LOS_capped] <= CurrentVal), [Freq])
			    )
			RETURN
			    MINX(
			        FILTER(CumulativeTable, [CumFreq] >= TotalCount * 0.75),
			        'Fact_Discharges'[LOS_capped]
			    )
		formatString: 0
		lineageTag: 0ac194df-1827-426d-ad18-ab0a4258133f

	measure 'National P25 (Same Type)' =
			
			CALCULATE(
			    [P25],
			    ALL('Hospital'),
			    VALUES('Fact_Discharges'[healthcare facility type])
			)
		formatString: 0
		lineageTag: 80b65891-5248-48d0-97ab-0a388127ca52

	measure 'National Median (Same Type)' =
			
			CALCULATE(
			    [Median],
			    ALL('Hospital'),
			    VALUES('Fact_Discharges'[healthcare facility type])
			)
		formatString: 0
		lineageTag: 33f3f480-1cfa-4445-aa74-4699c79eaff9

	measure 'National P75 (Same Type)' =
			
			CALCULATE(
			    [P75],
			    ALL('Hospital'),
			    VALUES('Fact_Discharges'[healthcare facility type])
			)
		formatString: 0
		lineageTag: 0ad637cb-89bc-4b53-94ca-63fded68d0b5

	measure '% Public Discharges' =
			
			VAR TotalAll =
			    CALCULATE(COUNTROWS('Fact_Discharges'), REMOVEFILTERS('Fact_Discharges'[healthcare facility type]))
			VAR PublicCount =
			    CALCULATE(
			        COUNTROWS('Fact_Discharges'),
			        REMOVEFILTERS('Fact_Discharges'[healthcare facility type]),
			        'Fact_Discharges'[healthcare facility type] = "Public"
			    )
			RETURN
			    DIVIDE(PublicCount, TotalAll)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5351e2a9-d6f1-443b-8189-9c7e7cd98139

	measure '% Private Discharges' =
			
			VAR TotalAll =
			    CALCULATE(COUNTROWS('Fact_Discharges'), REMOVEFILTERS('Fact_Discharges'[healthcare facility type]))
			VAR PrivateCount =
			    CALCULATE(
			        COUNTROWS('Fact_Discharges'),
			        REMOVEFILTERS('Fact_Discharges'[healthcare facility type]),
			        'Fact_Discharges'[healthcare facility type] = "Private"
			    )
			RETURN
			    DIVIDE(PrivateCount, TotalAll)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 43c9ef2f-1564-4563-a27e-1a9920fb6612

	measure 'Total Discharges' = COUNTROWS('Fact_Discharges')
		formatString: 0
		lineageTag: 8fadc2af-991d-457f-9eed-81a083375df9

	measure 'Public LOS P25' =
			
			CALCULATE([P25], 'Fact_Discharges'[healthcare facility type] = "Public")
		formatString: 0
		lineageTag: 6b7a5c16-057c-4f8e-b908-9e980c24a9c3

	measure 'Public Median LOS' =
			
			CALCULATE([Median], 'Fact_Discharges'[healthcare facility type] = "Public")
		formatString: 0
		lineageTag: 4c3f75a7-c817-4d20-98b0-5f282e6ee6e0

	measure 'Public LOS P75' =
			
			CALCULATE([P75], 'Fact_Discharges'[healthcare facility type] = "Public")
		formatString: 0
		lineageTag: 72daded8-304d-4e4b-b767-1f4e38605dc3

	measure 'Private LOS P25' =
			
			CALCULATE([P25], 'Fact_Discharges'[healthcare facility type] = "Private")
		formatString: 0
		lineageTag: 7dcd2a06-d79f-466d-b960-d5fdbabf40fb

	measure 'Private Median LOS' =
			
			CALCULATE([Median], 'Fact_Discharges'[healthcare facility type] = "Private")
		formatString: 0
		lineageTag: ec6671e0-f224-4e72-b2d4-13ae47f92d1f

	measure 'Private LOS P75' =
			
			CALCULATE([P75], 'Fact_Discharges'[healthcare facility type] = "Private")
		formatString: 0
		lineageTag: 44a6731a-1478-49a5-a1a5-b33de2a84f5e

	measure 'Total LOS Days' = SUM('Fact_Discharges'[LOS_capped])
		formatString: 0
		lineageTag: a50e534e-e3db-4e15-be91-2c71a43fb3d5

	measure 'Total LOS Days (All Chapters)' =
			
			VAR SelectedChapter = SELECTEDVALUE('Chapter List'[chapter names])
			RETURN
			CALCULATE(
			    [Total LOS Days],
			    TREATAS({SelectedChapter}, 'Diagnosis'[chapter names]),
			    ALL('Diagnosis')
			)
		formatString: 0
		lineageTag: 6b81f337-7ee7-4a33-9726-7fed4a0658ca

	measure 'Total LOS Days (All Groups)' =
			
			VAR SelectedGroup = SELECTEDVALUE('Group List'[group names])
			RETURN
			CALCULATE(
			    [Total LOS Days],
			    TREATAS({SelectedGroup}, 'Diagnosis'[group names]),
			    ALL('Diagnosis')
			)
		formatString: 0
		lineageTag: fcae6de2-f9b6-4dac-8b1e-46adcdfb6a69

	measure 'Total Chapters' = COUNTROWS(ALL('Diagnosis'[chapter names]))
		formatString: 0
		lineageTag: c8fdcd3f-2826-4c70-8878-b9f07bf611e2

	measure 'Total Groups' = COUNTROWS(ALL('Diagnosis'[group names]))
		formatString: 0
		lineageTag: cfe94785-9387-4d80-935b-0fc019ff9ed6

	measure 'Chapter Rank Display' =
			
			"Rank " & [Chapter LOS Rank] & " of " & [Total Chapters] & " chapters"
		lineageTag: 45aff8cc-b26e-48a5-b2c9-bfe254cfb052

	measure 'Group Rank Display' =
			
			"Rank " & [Group LOS Rank] & " of " & [Total Groups] & " groups"
		lineageTag: 9b1e8bf1-ba77-402c-a52d-edb93b0f72a0

	column sex
		dataType: string
		lineageTag: 6864dc0b-1817-4b8d-9153-731cb6e365a4
		summarizeBy: none
		sourceColumn: sex

		annotation SummarizationSetBy = Automatic

	column age
		dataType: string
		lineageTag: 42d186ed-ffb5-406f-8a12-fdee0b95abb3
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column 'health insurance'
		dataType: string
		lineageTag: 6f653b91-87ec-4c37-a6f0-226f7cd98539
		summarizeBy: none
		sourceColumn: health insurance

		annotation SummarizationSetBy = Automatic

	column 'healthcare facility name'
		dataType: string
		lineageTag: 2b7e8ee0-782d-41db-bb7d-5ceb0a1b54e5
		summarizeBy: none
		sourceColumn: healthcare facility name

		annotation SummarizationSetBy = Automatic

	column 'length of stay'
		dataType: int64
		formatString: 0
		lineageTag: 6226781a-746d-4beb-9b56-6cbe09a7a7a3
		summarizeBy: sum
		sourceColumn: length of stay

		annotation SummarizationSetBy = Automatic

	column 'discharge condition'
		dataType: string
		lineageTag: 93b56e80-3da9-49c6-85c0-e125401cc792
		summarizeBy: none
		sourceColumn: discharge condition

		annotation SummarizationSetBy = Automatic

	column 'primary diagnosis code'
		dataType: string
		lineageTag: d6c12b6e-e157-4857-8425-53ecf42cacbb
		summarizeBy: none
		sourceColumn: primary diagnosis code

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 773ec7d2-894c-40d9-9804-d68889fcf7d5
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column LOS_capped
		dataType: int64
		formatString: 0
		lineageTag: 1e04b034-3538-4209-b13e-f984da19810b
		summarizeBy: sum
		sourceColumn: LOS_capped

		annotation SummarizationSetBy = Automatic

	column 'healthcare facility type'
		dataType: string
		lineageTag: 9e7ba1d9-c042-4701-8d7a-85c8167f42ee
		summarizeBy: none
		sourceColumn: healthcare facility type

		annotation SummarizationSetBy = Automatic

	partition Fact_Discharges = m
		mode: import
		source =
				let
				    Source = #"Discharges_2001-2024_bivariate_final",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"primary diagnosis name", "chapter codes", "chapter names", "group codes", "group names"}),
				    #"Trimmed Text" = Table.TransformColumns(#"Removed Columns",{{"primary diagnosis code", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"primary diagnosis code", Text.Clean, type text}}),
				    #"Trimmed Text1" = Table.TransformColumns(#"Cleaned Text",{{"healthcare facility name", Text.Trim, type text}}),
				    #"Cleaned Text1" = Table.TransformColumns(#"Trimmed Text1",{{"healthcare facility name", Text.Clean, type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Cleaned Text1",{{"primary diagnosis code", Text.Upper, type text}}),
				    #"Trimmed Text2" = Table.TransformColumns(#"Uppercased Text",{{"healthcare facility type", Text.Trim, type text}}),
				    #"Cleaned Text2" = Table.TransformColumns(#"Trimmed Text2",{{"healthcare facility type", Text.Clean, type text}})
				in
				    #"Cleaned Text2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

