table Hospital
	lineageTag: 3f068ffd-0026-4795-8c71-0d17f860edb7

	column 'healthcare facility type'
		dataType: string
		lineageTag: f5884256-981f-48a0-9672-2d84a0de11da
		summarizeBy: none
		sourceColumn: healthcare facility type

		annotation SummarizationSetBy = Automatic

	column 'healthcare facility name'
		dataType: string
		lineageTag: 0124de33-5e4b-41b6-b5e3-35b03fac07db
		summarizeBy: none
		sourceColumn: healthcare facility name

		annotation SummarizationSetBy = Automatic

	partition Hospital = m
		mode: import
		source =
				let
				    Source = #"Discharges_2001-2024_bivariate_final",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"healthcare facility type", "healthcare facility name"}),
				    #"Trimmed Text" = Table.TransformColumns(#"Removed Other Columns",{{"healthcare facility type", Text.Trim, type text}, {"healthcare facility name", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"healthcare facility type", Text.Clean, type text}, {"healthcare facility name", Text.Clean, type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Cleaned Text", {"healthcare facility name"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

